---
- name: Run the test playbook
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Get the username running this playbook
      local_action: command whoami
      register: username_on_the_host
    - name: Display the User name
      ansible.builtin.debug:
        msg: "Hello User {{ username_on_the_host.stdout }} from Jenkins and Ansible!!"
    - name: Copy
      hosts: servers
      copy:
        src: /var/lib/jenkins/workspace/clojure-api/target/hello-server-0.1.0-SNAPSHOT-standalone.jar
        dest: /home/ec2-user/server